### ISSUE TITLE
add txtTarget to readme

### ISSUE THREAD

**Issue by mhgolij** [davicotico/Menu-Editor#8]
txtTarget for link work correctly but there is nothing about that in readme

version : 1.1.1

**Comment by davicotico** [comment]
Hi @mhgolij . Thanks for the feedback.

Actually, the "target" attribute is working because MenuEditor accepts custom attributes, as you can see [here](https://github.com/davicotico/Menu-Editor?tab=readme-ov-file#add-a-new-item). You can add any other attributes to the menu item.
